baseURL = "https://aegisonic.org/"
languageCode = "en-us"

title = "Aegisonic"
description= "An adaptive headset designed to reduce auditory overstimulation & distress in autism."

[menus]
    [[menus.main]]
        name = 'About'
        url = '/about'
        weight = 1

    [[menus.main]]
        name = 'Gallery'
        url = '/gallery'
        weight = 2

[params]
    tagline = "Equitable acoustics"

    [params.social]
        instagram = false
        linkedin = false
        facebook = false
        twitter = false
        threads = false
        bluesky = false

    [params.contact]
        phone = false
        email = false
    
    [params.hero]
        link = "/about"
        cta = "Learn more"

[module]
    [module.hugoVersion]
        extended = false
        min = "0.146.0"

[caches]
  [caches.images]
    dir = ':cacheDir/images'